#!/usr/bin/env php
<?php

// if you don't want to setup permissions the proper way, just uncomment the following PHP line
// read http://symfony.com/doc/current/book/installation.html#configuration-and-setup for more information
umask(0002);

set_time_limit(0);

use App\Application;

// the autoloader
$loader = require __DIR__ . '/../vendor/autoload.php';

$application = new Application("App");
$application->run();
